### ISSUE TITLE
建议: 查看插件介绍支持点击图片跳转

### ISSUE THREAD

**Issue by CV-Devlau** [halo-dev/plugin-app-store#32]
现在指定点击插件的标题才能弹出插件介绍不太方便，建议点击图片也可以

**Comment by ruibaby** [comment]
Hi @CV-Devlau ，有兴趣来处理这个问题吗？

**Comment by CV-Devlau** [comment]
> Hi @CV-Devlau ，有兴趣来处理这个问题吗？

可以，我晚上可以加一下
