### ISSUE TITLE
应用版本校验与 Halo 后端有差异

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/plugin-app-store#38]
如图：

<img width="1486" alt="image" src="https://github.com/halo-dev/plugin-app-store/assets/21301288/e8c68d5c-3238-4023-aa08-5c0a5637acc4">

如果主题或者插件是一个固定的版本号，而不是形如 `>=2.6.0` 则提示版本不兼容，但实际上这个主题是可以在 Halo 中安装的。

相关代码：https://github.com/halo-dev/plugin-app-store/blob/309e5549220ccd76ea9ba5707fe235be4ac1e32a/console/src/composables/use-app-compare.ts#L63

使用的库是：https://www.npmjs.com/package/semver

/kind bug

**Comment by ruibaby** [comment]
cc @guqing

**Comment by guqing** [comment]
后端做了处理，自动重写了规则，如果版本号是确定的版本号并且不支持固定版本号就会自动重写为 >=
<img width="906" alt="image" src="https://github.com/halo-dev/plugin-app-store/assets/38999863/42e744f1-6483-4387-80b9-455a0d9bddd8">

如果期望支持固定值的版本号校验，可以修改 halo 的默认值来避免重写为 `>=`，需要支持吗
<img width="745" alt="image" src="https://github.com/halo-dev/plugin-app-store/assets/38999863/c60c5467-e7dd-4f50-91b2-c3a7c6c5b567">

**Comment by guqing** [comment]
统一一下就好了，如果需要支持固定的版本号，比如必须在 2.6.0 版本才能使用其他的都不行，那么就需要 halo 支持一下固定版本号

**Comment by ruibaby** [comment]
应用市场适配 Halo现在的规则吧，毕竟应用市场后面才有。

晚点我会提交 PR 来适配。
