### ISSUE TITLE
主题更新后，在应用市场显示为未安装状态

### ISSUE THREAD

**Issue by bluezsd** [halo-dev/plugin-app-store#41]
在应用市场点击更新Joe3.0主题，主题会变成未安装状态，需要重新安装一次才行。

**Comment by ruibaby** [comment]
目前 Halo 从本地升级主题不会保留 annotations 信息，所以如果你原来是从应用市场下载的，然后进行了本地升级操作，这个时候就会丢失关联信息。 

建议直接从内置的应用市场进行升级。

**Comment by ruibaby** [comment]
可以复现，感谢反馈。

/kind bug
