### ISSUE TITLE
请问如何在https://www.halo.run/console/users/-/?tab=pat 创建个人令牌

### ISSUE THREAD

**Issue by shmilyabyy** [halo-dev/plugin-app-store#43]
如题

**Comment by ruibaby** [comment]
https://github.com/halo-dev/plugin-app-store/releases/tag/v1.0.0-beta.1

Personal Access Token 需要 2.10 才能支持，但目前 Halo 官网还未升级，我们会在发布 2.10 之前升级官网的版本。

**Comment by ruibaby** [comment]
现在已经可以了。

/close
