### ISSUE TITLE
不识别安装应用商店之前已经安装的插件

### ISSUE THREAD

**Issue by Contour-D** [halo-dev/plugin-app-store#51]
![屏幕截图 2023-12-25 184703](https://github.com/halo-dev/plugin-app-store/assets/40132326/3628b2f4-2450-4f7e-93b5-ad7689709a12)
瞬间是我在安装应用插件之前安装的
![屏幕截图 2023-12-25 184712](https://github.com/halo-dev/plugin-app-store/assets/40132326/da6169b1-a510-4133-a7b8-c0a2e12fe6c0)
安装完应用商店后瞬间这里显示可以安装，未显示已安装
![屏幕截图 2023-12-25 184719](https://github.com/halo-dev/plugin-app-store/assets/40132326/57e11b64-c22a-4f98-8de2-d3e7ec4b6bb9)
点安装后是可以重新安装的

**Comment by ruibaby** [comment]
现在只能在应用市场安装才能建立绑定。具体请看：https://github.com/halo-dev/plugin-app-store#2-应用关联

/kind support
